version: "3.8"

services:
  db:
    image: postgres:15
    container_name: quiz-app-db-dev
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-quizuser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-quizpassword}
      - POSTGRES_DB=${DB_NAME:-quizdb}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - quiz-network-dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-quizuser} -d ${DB_NAME:-quizdb}"]
      interval: 10s
      timeout: 5s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: quiz-app-pgadmin-dev
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data_dev:/var/lib/pgadmin
    networks:
      - quiz-network-dev
    depends_on:
      - db
    restart: unless-stopped

networks:
  quiz-network-dev:
    driver: bridge

volumes:
  postgres_data_dev:
  pgadmin_data_dev: 