version: "3.8"

services:
  # База данных PostgreSQL
  db:
    image: postgres:15
    container_name: quiz-app-db
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-quizuser}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-quizpassword}
      - POSTGRES_DB=${DB_NAME:-quizdb}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-quizuser} -d ${DB_NAME:-quizdb}",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  # pgAdmin - веб-интерфейс для PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: quiz-app-pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - quiz-network
    depends_on:
      - db
    restart: unless-stopped

  # Бэкенд NestJS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: quiz-app-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER:-quizuser}
      - DB_PASSWORD=${DB_PASSWORD:-quizpassword}
      - DB_NAME=${DB_NAME:-quizdb}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}
      - TYPEORM_SYNCHRONIZE=true
      - RUN_SEED=${RUN_SEED:-true}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - quiz-network
    restart: unless-stopped

  # Фронтенд React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: quiz-app-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - quiz-network
    restart: unless-stopped

networks:
  quiz-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
