version: "3.8"

services:
  db:
    image: postgres:15
    container_name: quiz-app-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=quizuser
      - POSTGRES_PASSWORD=quizpassword
      - POSTGRES_DB=quizdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - quiz-network
    restart: unless-stopped

  backend:
    image: quiz-app-backend:latest
    container_name: quiz-app-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=quizuser
      - DB_PASSWORD=quizpassword
      - DB_NAME=quizdb
      - JWT_SECRET=simple-jwt-secret
      - TYPEORM_SYNCHRONIZE=true
    depends_on:
      - db
    networks:
      - quiz-network
    restart: unless-stopped

  frontend:
    image: quiz-app-frontend:latest
    container_name: quiz-app-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - quiz-network
    restart: unless-stopped

networks:
  quiz-network:
    driver: bridge

volumes:
  postgres_data: 