import { QuestionType } from "./types";

// Константы для шагов создания теста
export const CREATE_QUIZ_STEPS = {
  QUIZ_INFO: 0,
  QUESTIONS: 1,
};

// Константы для названий страниц
export const PAGE_TITLES = {
  HOME: "Доступные тесты",
  LOGIN: "Вход в систему",
  REGISTER: "Регистрация",
  PROFILE: "Мой профиль",
  QUIZZES: "Тесты",
  CREATE_QUIZ: "Создать новый тест",
  IMPORT_QUIZ: "Импорт теста из файла",
  EDIT_QUIZ: "Редактировать тест",
  TAKE_QUIZ: "Прохождение теста",
  RESULTS: "Результаты",
  DASHBOARD: "Панель управления",
  USERS: "Пользователи",
  SETTINGS: "Настройки",
  NOT_FOUND: "404 - Страница не найдена",
  NOT_AUTHORIZED: "403 - Доступ запрещён",
};

// Константы для маршрутов
export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  PROFILE: "/profile",
  QUIZZES: "/quizzes",
  CREATE_QUIZ: "/create",
  IMPORT_QUIZ: "/import-quiz",
  EDIT_QUIZ: (id: number) => `/edit-quiz/${id}`,
  TAKE_QUIZ: (id: number) => `/quiz/${id}`,
  RESULTS: "/results",
  QUIZ_RESULTS: (id: number) => `/results/${id}`,
  DASHBOARD: "/dashboard",
  USERS: "/users",
  SETTINGS: "/settings",
  NOT_FOUND: "*",
  NOT_AUTHORIZED: "/not-authorized",
};

// Настройки для различных типов вопросов
export const QUESTION_TYPE_CONFIG = {
  [QuestionType.SINGLE_CHOICE]: {
    label: "Один из списка",
    defaultOptions: ["", "", "", ""],
    canAddOptions: true,
  },
  [QuestionType.MULTIPLE_CHOICE]: {
    label: "Несколько из списка",
    defaultOptions: ["", "", "", ""],
    canAddOptions: true,
  },
  [QuestionType.TRUE_FALSE]: {
    label: "Верно/Неверно",
    defaultOptions: ["Верно", "Неверно"],
    canAddOptions: false,
  },
  [QuestionType.MATCHING]: {
    label: "Сопоставление",
    defaultOptions: ["", ""],
    canAddOptions: true,
  },
};

// Сообщения и тексты
export const MESSAGES = {
  ERRORS: {
    CREATE_QUIZ: "Не удалось создать тест. Пожалуйста, попробуйте снова.",
    UPDATE_QUIZ: "Не удалось обновить тест. Пожалуйста, попробуйте снова.",
    CREATE_QUESTION: "Не удалось создать вопрос. Пожалуйста, попробуйте снова.",
    INVALID_QUESTIONS: "Пожалуйста, заполните все вопросы с вариантами ответов и отметьте правильные ответы.",
    LOGIN_FAILED: "Неверное имя пользователя или пароль",
    REGISTER_FAILED: "Ошибка регистрации. Пожалуйста, проверьте данные и попробуйте снова.",
    UNAUTHORIZED: "Вы не авторизованы для выполнения этого действия.",
    SERVER_ERROR: "Произошла ошибка на сервере. Пожалуйста, попробуйте позже.",
    QUIZ_NOT_FOUND: "Тест не найден.",
    QUESTION_NOT_FOUND: "Вопрос не найден.",
    RESULT_NOT_FOUND: "Результат не найден.",
    USER_NOT_FOUND: "Пользователь не найден.",
    LOAD_QUIZZES_ERROR: "Ошибка загрузки тестов",
    LOAD_QUESTIONS_ERROR: "Ошибка загрузки вопросов",
    LOAD_RESULTS_ERROR: "Ошибка загрузки результатов",
    LOAD_USERS_ERROR: "Ошибка загрузки пользователей",
  },
  SUCCESS: {
    QUIZ_CREATED: "Тест успешно создан!",
    QUIZ_UPDATED: "Тест успешно обновлен!",
    QUIZ_DELETED: "Тест успешно удален!",
    LOGIN_SUCCESS: "Вы успешно вошли в систему!",
    REGISTER_SUCCESS: "Регистрация прошла успешно!",
    ANSWER_SUBMITTED: "Ответ отправлен!",
    QUIZ_COMPLETED: "Тест успешно завершен!",
    USER_UPDATED: "Пользователь успешно обновлен!",
    USER_DELETED: "Пользователь успешно удален!",
    PASSWORD_CHANGED: "Пароль успешно изменен!",
    PROFILE_UPDATED: "Профиль успешно обновлен!",
  },
  QUIZ_CREATION: {
    TITLE: "Создать новый тест",
    QUIZ_INFO_TITLE: "Информация о тесте",
    QUIZ_INFO_DESCRIPTION: "Введите основные данные для вашего теста.",
    QUIZ_TITLE_PLACEHOLDER: "Введите название теста",
    QUIZ_DESCRIPTION_PLACEHOLDER: "Введите описание теста",
    NEXT_BUTTON: "Далее: Добавить вопросы",
    QUESTIONS_TITLE: "Вопросы",
    QUESTIONS_DESCRIPTION: "Добавьте вопросы к вашему тесту.",
    QUESTION_TEXT_PLACEHOLDER: "Введите текст вопроса",
    ADD_QUESTION_BUTTON: "Добавить вопрос",
    DELETE_QUESTION_BUTTON: "Удалить",
    BACK_BUTTON: "Назад",
    SUBMIT_BUTTON: "Создать тест",
    SUBMITTING_BUTTON: "Отправка...",
  },
  QUIZ_EDITING: {
    TITLE: "Редактировать тест",
    QUIZ_INFO_TITLE: "Редактирование информации о тесте",
    QUIZ_INFO_DESCRIPTION: "Измените основные данные для вашего теста.",
    QUIZ_TITLE_PLACEHOLDER: "Введите название теста",
    QUIZ_DESCRIPTION_PLACEHOLDER: "Введите описание теста",
    SAVE_BUTTON: "Сохранить изменения",
    SAVING_BUTTON: "Сохранение...",
    CANCEL_BUTTON: "Отмена",
  },
  QUESTION_TYPES: {
    TYPE_LABEL: "Тип вопроса",
    TYPE_PLACEHOLDER: "Выберите тип вопроса",
    OPTIONS_LABEL: "Варианты ответов",
    MATCHING_LABEL: "Сопоставления",
    CORRECT_ANSWER_LABEL: "Правильный ответ",
    OPTION_PLACEHOLDER: (index: number) => `Вариант ${index + 1}`,
    KEY_PLACEHOLDER: (index: number) => `Ключ ${index + 1}`,
    VALUE_PLACEHOLDER: (index: number) => `Значение ${index + 1}`,
    ADD_OPTION_BUTTON: "Добавить вариант",
    ADD_PAIR_BUTTON: "Добавить пару",
    MARK_CORRECT_BUTTON: "Сделать правильным",
    IS_CORRECT_BUTTON: "✓ Правильный",
    SELECT_BUTTON: "Выбрать",
    IS_SELECTED_BUTTON: "✓ Выбран",
  },
  COMMON: {
    SAVE_BUTTON: "Сохранить",
    CANCEL_BUTTON: "Отмена",
    DELETE_BUTTON: "Удалить",
    EDIT_BUTTON: "Редактировать",
    VIEW_BUTTON: "Просмотр",
    SUBMIT_BUTTON: "Отправить",
    LOADING: "Загрузка...",
    CONFIRM_DELETE: "Вы уверены, что хотите удалить это?",
    YES: "Да",
    NO: "Нет",
    GO_HOME: "На главную",
    BACK: "Назад",
    NEXT: "Далее",
    PREVIOUS: "Назад",
    EMPTY_DATA: "Нет данных",
    NOT_FOUND_MESSAGE: "Извините, но страница, которую вы пытаетесь посетить, не существует.",
    NOT_AUTHORIZED_MESSAGE: "У вас нет прав для доступа к этой странице.",
  },
  QUIZZES: {
    EMPTY_QUIZZES: "Тесты не найдены",
    CREATE_FIRST_QUIZ: "Начните с создания своего первого теста!",
    NO_AVAILABLE_QUIZZES: "В данный момент нет доступных тестов.",
    AUTHOR: "Автор",
    UNKNOWN_AUTHOR: "Неизвестный пользователь",
  },
}; 